### PR TITLE
MNT: Re-rendered with conda-smithy 2.0.1

### PR DESCRIPTION
**Pull request by dolfim**

### CODE REVIEW

**Comment by dolfim** [comment]
Boost is not found because of conda-forge/boost-feedstock#29.

**Comment by jakirkham** [comment]
The new `boost` packages appear to be out. Are you still having issues here?

**Comment by dolfim** [comment]
Last time I forced a rebuild (on travis) it was still pulling the build _3. I will wait a moment and try again.

Circle CI instead complains about this:
```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - alps 2.3.0 np112py27_blas_openblas_2
  - numpy 1.12*
Use "conda info <package>" to see the dependencies for each package.
```
any idea? in case I can temporary disable numpy 1.12.

**Comment by dolfim** [comment]
The issue above is because I forgot to bump the build version.

Since matplotlib is not yet available for numpy 1.12, this will wait.

**Comment by jakirkham** [comment]
I think the `matplotlib` issue has been addressed.

**Comment by jakirkham** [comment]
Have you retried this @dolfim? Might be time to do a fresh re-render as well.

**Comment by dolfim** [comment]
Didn't try recently, but currently the main problem is the long compile time. Unfortunately with the change in travis a few months ago I never managed to finished a compilation. Maybe I should plan to spend a bit of time in splitting up the package..

**Comment by jakirkham** [comment]
That may be reasonable. Also might want to give `ninja` a look. Should be pretty easy to try if you are already using CMake.

**Pull request closed without merging**
